### ISSUE TITLE
Preview gradle files

### ISSUE THREAD

**Issue by vrunoa** [sindresorhus/quick-look-plugins#29]
Just created this Quicklook plugin to preview .gradle files. A quick way to check; android project version, target sdk, dependencies, package name.

<a href="https://github.com/Urucas/QLGradle">https://github.com/Urucas/QLGradle</a>

Useful for android devs.

**Comment by sindresorhus** [comment]
How is it better than just viewing the file?

**Comment by vrunoa** [comment]
There's no default app on OSX to open .gradle files, so you have to open it with some editor. The idea of creating this plugin was to avoid opening a text editor for a quick preview.

**Comment by sindresorhus** [comment]
:palm_tree: Since it doesn't give any enhanced view other than the plain text file it could just as well be added to `QLColorCode` or `QLStephen` instead. Happy to reconsider in the future if you decide to make an enhanced view. 

See https://github.com/sindresorhus/quick-look-plugins#provisionql as an example. :palm_tree:
